OPENAI_API_KEY = "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"
HUGGINGFACE_KEY = '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'
db_host = 'gaeni.org'
db_user = 'n1577918_admin-spw'
db_pass = 'jKCdeSB5EMgHf@9'
db_data = 'n1577918_spw-ai'